.github/

diff --git a/.github/workflows/ebs.yaml b/.github/workflows/ebs.yaml
--- a/.github/workflows/ebs.yaml
+++ b/.github/workflows/ebs.yaml
@@ -233,17 +233,28 @@ jobs:
           fi
 
         
-      # Check Application
+      # Step 3: Check if Elastic Beanstalk Application Exists
       - name: Check if Elastic Beanstalk Application Exists
         id: check-application
         run: |
-          if aws elasticbeanstalk describe-applications --application-names $APPLICATION_NAME >/dev/null 2>&1; then
-            echo "application_exists=true" >> $GITHUB_ENV
-            echo "Application exists: $APPLICATION_NAME"
-          else
-            echo "application_exists=false" >> $GITHUB_ENV
-            echo "Application does not exist: $APPLICATION_NAME"
-          fi
+          for i in {1..3}; do
+            RESULT=$(aws elasticbeanstalk describe-applications --application-names "$APPLICATION_NAME" --query 'Applications[0].ApplicationName' --output text 2>/dev/null || echo "NOT_FOUND")
+            if [ "$RESULT" == "NOT_FOUND" ] || [ "$RESULT" == "None" ]; then
+              if [ "$i" -lt 3 ]; then
+                echo "Application not found. Retrying in 10 seconds..."
+                sleep 10
+              else
+                echo "application_exists=false" >> $GITHUB_ENV
+                echo "Application does not exist: $APPLICATION_NAME"
+                break
+              fi
+            else
+              echo "application_exists=true" >> $GITHUB_ENV
+              echo "Application exists: $APPLICATION_NAME"
+              break
+            fi
+          done
+
 
       # Create Application
       - name: Create Elastic Beanstalk Application
@@ -257,7 +268,7 @@ jobs:
               break
             else
               echo "Application creation failed. Retrying in 10 seconds..."
-              sleep 10
+              sleep 20
             fi
           done
 
@@ -328,3 +339,16 @@ jobs:
           aws elasticbeanstalk update-environment \
             --environment-name $ENVIRONMENT_NAME \
             --version-label ${{ github.sha }}
+
+      # Check Environment Health
+      - name: Check Environment Health
+        run: |
+          HEALTH=$(aws elasticbeanstalk describe-environments \
+            --application-name $APPLICATION_NAME \
+            --environment-name $ENVIRONMENT_NAME \
+            --query 'Environments[0].Health' --output text)
+          if [[ "$HEALTH" != "Green" ]]; then
+            echo "Environment health is not Green: $HEALTH"
+            exit 1
+          fi
+          
